name: Build Python package

on:
  pull_request:
  push:
    branches: [ "main" ]
    tags:
      # Run on version tags
      - '*.*.*'

env:
  ZIG_VERSION: 0.15.2

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-13 is an intel runner, macos-14 is apple silicon
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Install Zig
        uses: mlugg/setup-zig@v2.0.5
        with:
          version: ${{ env.ZIG_VERSION }}
      - run: |
          echo "ZIG_PATH=$(dirname $(which zig))" >> $GITHUB_ENV
      - name: Build wheels
        uses: pypa/cibuildwheel@v3.1.0
        env:
          CIBW_BUILD: 'cp313-*'
          CIBW_ARCHS_LINUX: 'x86_64'
          CIBW_ENVIRONMENT: 'PATH=$PATH:/host/${{ env.ZIG_PATH }}/'
          CIBW_REPAIR_WHEEL_COMMAND_MACOS: ""
        with:
          output-dir: wheelhouse
      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ runner.arch }}
          path: ./wheelhouse/*.whl
